### ISSUE TITLE
Cannot run on Debian Jessie

### ISSUE THREAD

**Issue by wiibaa** [runkitdev/demokit#5]
Hi, thanks for this promising initiative, is is still a macOS only project as read in other issues?

Under Debian Jessie Node 4.4.7, npm install is ok but running a freshly created project 
with command `demokit first-one/index.js` returns
    `/home/philippe/.nvm/versions/node/v4.4.7/lib/node_modules/demokit/electron/node_modules/electron/dist/electron /home: symbol lookup error: /home/philippe/.nvm/versions/node/v4.4.7/lib/node_modules/demokit/electron/node_modules/screen-recorder/build/Release/addon.node: undefined symbol: _ZN21ScreenRecorderWrapper4InitEN2v85LocalINS0_6ObjectEEE`

normal ?
If yes would be good to **state it in the first lines of README**

**Comment by justinmayer** [comment]
There is already a reference near the beginning of the README that states:
> Currently only macOS is supported, but you can help us change that!

Ergo, I believe this issue can be closed.

**Comment by wiibaa** [comment]
@justinmayer this was not there when I posted the issue ;)
